# Generated by Django 3.1.7 on 2021-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihazlar',
            name='btNumarasi',
            field=models.IntegerField(),
        ),
    ]
