# Generated by Django 3.1.7 on 2021-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210412_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefonlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isyeri', models.CharField(max_length=50)),
                ('personelAdi', models.CharField(max_length=50)),
                ('personelSoyadi', models.CharField(max_length=50)),
                ('personelTelefon', models.IntegerField()),
            ],
        ),
    ]
