# Generated by Django 3.1.7 on 2021-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_telefonlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gorevli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorevliNumarasi', models.IntegerField()),
                ('gorevliAdi', models.CharField(max_length=50)),
                ('gorevliSoyadi', models.CharField(max_length=50)),
                ('gorevliTelefon', models.CharField(max_length=50)),
            ],
        ),
    ]
