# Generated by Django 3.1.7 on 2021-04-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_gorevli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihazlar',
            name='btNumarasi',
            field=models.IntegerField(verbose_name='Bt Numarası'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='cihazDurum',
            field=models.CharField(max_length=50, verbose_name='Cihaz Durumu'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='cihazSahibi',
            field=models.CharField(max_length=50, verbose_name='Cihaz Sahibi'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='cihazTuru',
            field=models.CharField(max_length=20, verbose_name='Cihaz Türü,'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='domainAdi',
            field=models.CharField(max_length=14, verbose_name='Domain Adı'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='gelisNedeni',
            field=models.CharField(max_length=50, verbose_name='Geliş Nedeni'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='gelisTarihi',
            field=models.DateField(verbose_name='Geliş Tarihi'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='gorevli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.gorevli'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='isyeri',
            field=models.CharField(max_length=50, verbose_name='İşyeri Adı'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='markaAdi',
            field=models.CharField(max_length=50, verbose_name='Marka Adı'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='teslimTarihi',
            field=models.DateField(verbose_name='Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='cihazlar',
            name='yapilanIs',
            field=models.CharField(max_length=50, verbose_name='Yapılan İş'),
        ),
        migrations.AlterField(
            model_name='gorevli',
            name='gorevliAdi',
            field=models.CharField(max_length=50, verbose_name='Görevli Adı'),
        ),
        migrations.AlterField(
            model_name='gorevli',
            name='gorevliNumarasi',
            field=models.IntegerField(verbose_name='Görevli Numarası'),
        ),
        migrations.AlterField(
            model_name='gorevli',
            name='gorevliSoyadi',
            field=models.CharField(max_length=50, verbose_name='Görevli Soyadı'),
        ),
        migrations.AlterField(
            model_name='gorevli',
            name='gorevliTelefon',
            field=models.CharField(max_length=50, verbose_name='Gorevli Telefonu'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='isyeri',
            field=models.CharField(max_length=50, verbose_name='İşyeri Adı'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='personelAdi',
            field=models.CharField(max_length=50, verbose_name='Personel Adı'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='personelSoyadi',
            field=models.CharField(max_length=50, verbose_name='Personel Soyadı'),
        ),
        migrations.AlterField(
            model_name='telefonlar',
            name='personelTelefon',
            field=models.IntegerField(verbose_name='Personel Telefonu'),
        ),
    ]
